[package]
name = "tsc"
version = "0.1.0"
authors = ["tomiy <tomiy@tomiylab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.17"
lazy_static = "1.4.0"
regex = "1.5.5"
rustyline = "10.0.0"
text-colorizer = "1.0.0"
thiserror= "1"
